# Generated by Django 4.2.4 on 2023-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_todotask'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='is_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
