UNIVERSITIES = [
    'Universitatea de Vest "Vasile Goldiș" Arad',
    'Universitatea Transilvania Brașov',
    'Universitatea de Medicină și Farmacie "Carol Davila" București',
    'Universitatea de Medicină și Farmacie "Iuliu Hațieganu" Cluj-Napoca',
    'Universitatea "Ovidius" Constanța',
    'Universitatea de Medicină și Farmacie Craiova',
    'Facultatea de Medicină a Universității Galați',
    'Universitatea de Medicină și Farmacie "Grigore T. Popa" Iași',
    'Facultatea de Medicină a Universității Oradea',
    'Universitatea "Lucian Blaga" Sibiu',
    'Universitatea de Medicină și Farmacie Târgu Mureș',
    'Facultatea de Medicină a Universității „Titu Maiorescu"',
    'Universitatea de Medicină și Farmacie "Victor Babeș" Timișoara',
]

CITIES = [
    'Arad',
    'Brașov',
    'București - CAROL DAVILA',
    'București - TITU MAIORESCU',
    'Cluj-Napoca',
    'Constanța',
    'Craiova',
    'Galați',
    'Iași',
    'Oradea',
    'Sibiu',
    'Târgu Mureș',
    'Timișoara',
]

SPECIALITIES_PER_CATEGORY = [
    {'Specialităţi clinice - Adulţi':[
        'Medicină internă',
        'Cardiologie',
        'Gastroenterologie',
        'Hematologie',
        'Nefrologie',
        'Pneumologie',
        'Reumatologie',
        'Endocrinologie',
        'Dermato-venerologie',
        'Oncologie medicală',
        'Boli infecţioase',
        'Neurologie',
        'Psihiatrie',
        'Recuperare, medicină fizică şi balneologie',
        'Medicina muncii',
        'Medicină sportivă',
        'Diabet zaharat, nutriţie şi boli metabolice',
        'Geriatrie şi gerontologie',
        'Alergologie şi imunologie clinică',
        'Radioterapie',
        'Farmacologie clinică',
        'Medicină de familie',
        'Genetică medicală',
        'Medicină de urgenţă',
        'Expertiza medicală a capacităţii de muncă',
    ]},
    {'Specialităţi clinice - Copii':[
        'Pediatrie',
        'Neonatologie',
        'Neurologie pediatrică',
        'Psihiatrie pediatrică',
    ]},
    {'Specialităţi chirurgicale - Adulţi':[
        'Chirurgie generală',
        'Chirurgie cardiacă şi a vaselor mari',
        'Chirurgie vasculară',
        'Chirurgie toracică',
        'Urologie',
        'Chirurgie plastică - microchirurgie reconstructivă',
        'Neurochirurgie',
        'Otorinolaringologie',
        'Chirurgie maxilo- facială',
        'Oftalmologie',
        'Obstetrică-ginecologie',
        'Ortopedie şi traumatologie',
        'Anestezie şi terapie intensivă',
    ]},
     {'Specialităţi chirurgicale pediatrice':[
        'Chirurgie pediatrică',
        'Ortopedie pediatrică',
    ]},
    {"Specialitati paraclinice":[
        'Radiologie-imagistică medicală',
        'Medicină nucleară',
        'Anatomie patologică',
        'Medicină legală',
        'Medicină de laborator',
        'Epidemiologie',
        'Igienă',
        'Sănătate publică şi management',
    ]}
]
